### ISSUE TITLE
Windows 10 tmt TypeError

### ISSUE THREAD

**Issue by agentmirv** [cubing/tnoodle#220]
Hi, I'm getting a TypeError when I attempt to use the tmt script. I'm on Windows 10 and my Python version is 3.5.2. I'm just starting out with this codebase and any help would be great, thanks. The call stack for the error is below:

```
C:\GitHub\tnoodle>python tmt graph --descriptions
Hit excepthook! stderr.isatty: True stdin.isatty: True stdout.isatty: True
Traceback (most recent call last):
  File "tmt", line 1240, in <module>
    tmt._main()
  File "tmt", line 234, in _main
    self._loadTmtProjects()
  File "tmt", line 189, in _loadTmtProjects
    self._cdEntryPoint()
  File "tmt", line 173, in _cdEntryPoint
    setupGitHooks.setupGitHooksIfNotSetup()
  File "C:\GitHub\tnoodle\git-tools\setupGitHooks.py", line 19, in setupGitHooksIfNotSetup
    createSymlinkIfNotExistsOrStale(target, gitHooksFolder)
  File "C:\GitHub\tnoodle\git-tools\setupWindowsCygwinSymlinking.py", line 64, in createSymlinkIfNotExistsOrStale
    symlinkExists = os.path.islink(name)
  File "C:\GitHub\tnoodle\git-tools\setupWindowsCygwinSymlinking.py", line 18, in islink
    return readlink(path) != None
  File "C:\GitHub\tnoodle\git-tools\setupWindowsCygwinSymlinking.py", line 27, in readlink
    files = stdout.split('\n')
TypeError: a bytes-like object is required, not 'str'
> c:\github\tnoodle\git-tools\setupwindowscygwinsymlinking.py(27)readlink()
-> files = stdout.split('\n')
```

**Comment by jfly** [comment]
For a while, I did development on Windows, but eventually switched to Linux, and I haven't bothered to keep tmt working on Windows. You could try to get it working, but your best bet is going to be to use Linux. @pedrosino does his development inside of a vm. 

I'm going to close this because I don't want to add windows support myself, but I would be willing look at a PR that adds it if someone really wants to add it.
